### ISSUE TITLE
Add support of the delete_by_query method

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-client-python-async#2]
Add the method `delete_by_query` to be consistent with what is offered in the "algoliasearch-client-python" API client.

The code of the method in that client
https://github.com/algolia/algoliasearch-client-python/blob/6b8832fbc1d180ae41813c04bda2766757156822/algoliasearch/index.py#L239-L257

**Comment by PLNech** [comment]
I tried to tackle this with @aseure and @anthony. 

- We tried wrapping this as an async method, but `delete_by_query` uses `browse_all` which requires sync processing of records (`self.answer.get('cursor', None)` -> `AttributeError: '_asyncio.Future' object has no attribute 'get')`)

- We tried forwarding the method to the underlying synchronous `Client`, but as `algoliasearch-client-python-async` replaces the transport layer with asyncio's, we could not do synchronous network calls (`RuntimeError: Timeout context manager should be used inside a task`)

We concluded that a user should use `algoliasearch-client-python` for `delete_by_query`.

**Comment by LeoErcolanelli** [comment]
Just for the record, I implemented it in 40e5d6a058c26e9649218b09b2b4248db709e9ee
