### ISSUE TITLE
Release 1.3.1 not in PyPI

### ISSUE THREAD

**Issue by talaus-signifai** [algolia/algoliasearch-client-python-async#5]
Cannot install algoliasearchasync 1.3.1 from PyPI, latest version is [1.3.0](https://pypi.python.org/pypi/algoliasearchasync/1.3.0)

**Comment by PLNech** [comment]
@talaus-signifai: Good catch, sorry for the hassle! [Fixed](https://pypi.python.org/pypi/algoliasearchasync/1.3.1).
