### ISSUE TITLE
AttributeError: module 'aiohttp' has no attribute 'Timeout'

### ISSUE THREAD

**Issue by gmolau** [algolia/algoliasearch-client-python-async#6]
I'm currently testing this library with the Python >= 3.5.1 example from the README. Yet when running that exact same code with only the app_id, api_key, index_name and search terms replaced I get this error:

```
algoliasearch.helpers.AlgoliaException: ('Unreachable hosts: %s', {'<APP_ID>-dsn.algolia.net': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-2.algolianet.com': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-1.algolianet.com': 'ClientConnectionError: Connector is closed.', '<APP_ID>-3.algolianet.com': 'ClientConnectionError: Connector is closed.'})
```

"Unreachable host" would seem to indicate that the client can't connect to my index, but I have double checked the credentials and they do work fine with a synchronous client. Looking at [line 107](https://github.com/algolia/algoliasearch-client-python-async/blob/ffa4b62257bc1fe66bf714938a51c05990ec70a0/algoliasearchasync/transport.py#L107) of transport.py it seems that reaching the host is not actually the problem, but rather the integration of the aiohttp module. Could it be that this is related to Python 3.6? Is there a quick way to fix this?

My complete stack trace is this:

```
Unclosed connection
client_connection: Connection<ConnectionKey(host='<APP_ID>-2.algolianet.com', port=443, ssl=True)>
Traceback (most recent call last):
  File "algolia_async.py", line 19, in <module>
    complete = loop.run_until_complete(main(terms))
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "algolia_async.py", line 13, in main
    return await asyncio.gather(*searches)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 215, in coro
    res = yield from res
  File "<PROJECT_PATH>/venv/lib/python3.6/site-packages/algoliasearchasync/transport.py", line 107, in req
    raise AlgoliaException('Unreachable hosts: %s', exceptions)
algoliasearch.helpers.AlgoliaException: ('Unreachable hosts: %s', {'<APP_ID>-dsn.algolia.net': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-2.algolianet.com': "AttributeError: module 'aiohttp' has no attribute 'Timeout'", '<APP_ID>-1.algolianet.com': 'ClientConnectionError: Connector is closed.', '<APP_ID>-3.algolianet.com': 'ClientConnectionError: Connector is closed.'})
```

**Comment by LeoErcolanelli** [comment]
Hi @gmolau 
May I ask you what version of `aiohttp` you are using?

**Comment by gmolau** [comment]
@ercolanelli-leo I was using aiohttp 3.1.1.

**Comment by gmolau** [comment]
Note that the description above is pretty much obsolete, see #8 for what was actually the problem.

**Comment by LeoErcolanelli** [comment]
Fixed by https://github.com/algolia/algoliasearch-client-python-async/pull/10
